# 应用名称
server:
  port: 8088
spring:
  application:
    name: spring-flink-demo
  ######################kafka about config ##############################
  kafka:
    bootstrap-servers: localhost:9092
  ##########################producer about config##########################
    producer:
      acks: 1
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer.class
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer.class
  ##########################consumer about config##############################
    consumer:
      auto-commit-interval: 100
      enable-auto-commit: true
      group-id: kafka_group_test
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer.class
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer.class
    template:
      topic: test
      default-topic: test
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000

hbase:
  rootdir: hdfs://localhost:9000/hbase
  zookeeper:
    quorum: localhost
  client:
    period: 1000
  rpc:
    timeout: 1000